  unbound:
    container_name: unbound

    image: lkpot/unbound:1.24.0

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8953:8953/tcp"

    cap_drop:
      - ALL

    cap_add:
      - NET_BIND_SERVICE

    volumes:
      - ./unbound:/etc/unbound

    restart: unless-stopped
