services:
  unbound:
    container_name: unbound

    image: lkpot/unbound:latest

    network_mode: host

    cap_drop:
      - ALL

    cap_add:
      - NET_BIND_SERVICE

    expose:
      - "53"

    volumes:
      - ./etc-unbound:/etc/unbound

    restart: unless-stopped
